version: '3'

dotenv: ['.env']

tasks:
  check:
    cmds:
      - uv run ruff check inky-display
  fix:
    cmds:
      - uv run ruff check --fix inky-display
      - uv run ruff check --fix hack
  format:
    cmds:
      - uv run ruff format inky-display
      - uv run ruff format hack
  run:
    cmds:
      - uv run inky-display/main.py
  install-fonts:
    cmds:
      - uv run hack/download-fonts.py
  install-systemd:
    cmds:
      - "cp run-display.sh $HOME"
      - "mkdir -p $HOME/.config/systemd/user"
      - "cp run-display.service $HOME/.config/systemd/user" 
      - systemctl --user enable run-display.service
