name: check

on:
  push:
    branches: ["main"]
  pull_request:
  merge_group:


jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Setup Task
        uses: illbjorn/setup-task@178d62406bf0554c24e1bd76d1e4d8e94fc0a638 # main
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
      - name: Perform check
        shell: bash
        run: uv sync && task check
